import { useQuery, useQueryClient } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import { Sparkles, RefreshCw } from 'lucide-react';
import { fetchFundSummary } from '../lib/api';

export default function AISummary({ code }) {
  const queryClient = useQueryClient();

  const { data, isLoading, error, isFetching } = useQuery({
    queryKey: ['fundSummary', code],
    queryFn: () => fetchFundSummary(code),
    staleTime: 300_000,
    enabled: !!code,
    retry: false,
  });

  const result = data?.data;

  const handleRegenerate = () => {
    queryClient.invalidateQueries({ queryKey: ['fundSummary', code] });
  };

  return (
    <motion.div
      className="bg-card border border-border rounded-lg overflow-hidden"
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3, delay: 0.3 }}
    >
      <div className="flex items-center justify-between px-4 py-3 border-b border-border-subtle">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-accent" />
          <h3 className="font-mono font-bold text-sm text-foreground">AI Analysis</h3>
        </div>
        {result && (
          <button
            onClick={handleRegenerate}
            disabled={isFetching}
            className="flex items-center gap-1 px-2 py-1 text-[10px] font-mono text-muted hover:text-foreground transition-colors disabled:opacity-30"
          >
            <RefreshCw className={`w-3 h-3 ${isFetching ? 'animate-spin' : ''}`} />
            Regenerate
          </button>
        )}
      </div>

      <div className="px-4 py-4">
        {isLoading && <LoadingSkeleton />}

        {error && (
          <div className="text-center py-6">
            <p className="text-sm text-muted">
              {error.response?.status === 503
                ? 'AI service not configured.'
                : 'AI analysis unavailable'}
            </p>
            <button
              onClick={handleRegenerate}
              className="mt-2 px-3 py-1 text-xs font-mono text-accent hover:text-accent/80 transition-colors"
            >
              Retry
            </button>
          </div>
        )}

        {result && (
          <div>
            <p className="text-sm text-foreground/90 leading-relaxed whitespace-pre-wrap">
              {result.summary}
            </p>
            <div className="flex items-center gap-2 mt-4 pt-3 border-t border-border-subtle/30">
              <span className="text-[10px] text-muted">
                Generated by {result.model}
              </span>
              <span className="text-[10px] text-muted/50">·</span>
              <span className="text-[10px] text-muted">
                {new Date(result.generatedAt).toLocaleString('en-IN', {
                  day: '2-digit',
                  month: 'short',
                  year: 'numeric',
                  hour: '2-digit',
                  minute: '2-digit',
                })}
              </span>
            </div>
          </div>
        )}
      </div>
    </motion.div>
  );
}

function LoadingSkeleton() {
  return (
    <div className="space-y-3">
      {[1, 0.9, 0.95, 0.7].map((w, i) => (
        <div
          key={i}
          className="h-3 bg-background rounded animate-pulse"
          style={{ width: `${w * 100}%` }}
        />
      ))}
    </div>
  );
}
